### ISSUE TITLE
Can I use another postgreSQL version?

### ISSUE THREAD

**Issue by sillycube** [imixs/imixs-docker#38]
I am using postgres:11-alpine docker image in my docker-compose.yml file. But your Dockerfile is using postgres:9.6.1. 

When I run docker-compose up, it shows that:
pg_dump: server version: 11.2; pg_dump version: 9.6.11
pg_dump: aborting because of server version mismatch

So I must use an older version?

**Comment by rsoika** [comment]
no - you can run also newer versions of Postgress - Postgres:11 is fine

**Comment by rsoika** [comment]
note: the image just imports the JDBC Postgres Driver. This driver is based on version 9.x but it will also work fine with newer Postgress Server versions like 11. But of course you can upgrade the JDBC driver also by overwriting the image, or we can do this in this project. We just need to replace the jar file with a newer version.
