### ISSUE TITLE
Update to Postgres 12.2

### ISSUE THREAD

**Issue by Soleer** [imixs/imixs-docker#43]
The latest version of the Postgres image is on Postgres 12.2. Because of version mismatch backups are aborted by pg_dump. But the log still says the backup was successful at the end.

**Comment by rsoika** [comment]
ok, do you mean docker image "imixs/backup"  (https://github.com/imixs/imixs-docker/tree/master/backup)

So in case you are running a newer Postgres Server you think that we should increase the postgres version?

`postgresql-client-11   ==>  postgresql-client-12`

https://github.com/imixs/imixs-docker/blob/master/backup/Dockerfile

Or are you using the docker image "imixs/postgres" ? I think we can drop this image. I am personally only use the official postgres images and not this imixs/postgres image because the imixs/backup image is providing more features.

**Comment by Soleer** [comment]
Oh yes sorry! 
I tried to backup one of my Postgres databases with your imixs/backup image and it failed because of a version mismatch. Actually I didn't want to ask if you could update to 12.2 but that would be awesome! I just wanted to point out, that in case of version mismatch the backup won't work but your log will still say the backup was successful. At first I read just the last line of the log and was confused why there was no backup. I thought you might want to know that in this case the response in your log is wrong. 
Thank you for your response!

**Comment by rsoika** [comment]
I just wanted to upgrade the client verison to postgresql-client-12.

But the Debian Buster is not supporting postgres 12. It is still supporting official version 11. So in this case I see no chance to update the version without the risk to break other things. 

As you can see we are also supporting mariadb. For that reason we can not build this image on the official postgres image. 
So the only chance I see for you is that you copy the backup scripts into your own image. I guess you are running the official postgres image v12?

**Comment by rsoika** [comment]
Ok - you can try to run the imixs/postgres image.
This image is now based on postgres 12.2 and it contains the same backup scripts. 
https://hub.docker.com/repository/docker/imixs/postgres/tags?page=1

    imixs/postgres:1.2.11

Let me know if this works for your

**Comment by Soleer** [comment]
The backup works if I start it manually but it seems like there is no cron job starting? Maybe because it skips the database initialisation? I tried to start the backup_init.sh via command in docker-compose but I get a permission denied.

**Comment by rsoika** [comment]
Ok, I have now added the backup/restore/cron mechanism as it is implemented in the imixs/backup images. 
Can you test this new setup?
You just need to checkout the project from github. 
Next you can build the imixs/postgres Docker image locally with

```
$ cd imixs-docker/postgres
$ docker build --tag=imixs/postgres .
```

So you have the latest build on your machine. It would be great if you can test this and give your feedback.

**Comment by rsoika** [comment]
I have just added a dockerhub trigger for automated builds.
So in case you can not test the image locally, you can now also run it on your server. 
In this case use the latest build

     imixs/postgres:latest

**Comment by Soleer** [comment]
I tried it out but it seems like the backup_init script runs until "cron -f" and then it stops. No database and no cron job is running. But backup.sh ist working.

**Comment by rsoika** [comment]
I tested it by myself and also improved the documentation. Maybe it is confusing now. The image imixs/postgres is just providing a backup service. It does not start a postgres database. You need to start the postgres service separately . It is not a good design to combine different tasks in one service/image. Even if this was my plan when I started this image in the early beginning of my docker career ;-)

So start the backup image like this

```
docker run --name="postgres" -it --rm \
    -e SETUP_CRON="*/1 * * * *" \
    -e BACKUP_DB_PASSWORD="xxxxxxxxxxx" \
    -e BACKUP_DB_HOST="db" \
    -e BACKUP_DB_TYPE="POSTGRES" \
    -e BACKUP_DB="wordpress" \
    imixs/postgres
```

this will run the script every minute
